### ISSUE TITLE
Build Problems because `config.h` doesn't exist in repo

### ISSUE THREAD

**Issue by jamesETsmith** [pyscf/shciscf#1]
# Problem
The header file `config.h` doesn't exist in this extension repo and causes build failures.

# Possible Solution

Rather than depending on the pyscf source files, I think it makes more sense add the OMP related parts of `config.h` to `libSHCITools.c`. This makes the extension more standalone, which seems advantageous to me.

**Comment by fishjojo** [comment]
I simply included omp.h (see #3), as in setup.py openmp flags are added anyway.

**Comment by jamesETsmith** [comment]
Thanks @fishjojo! I'll update PR #2
